[package]
name = "verver"
version = "0.1.0"
edition = "2021"

[dependencies]
winnow = "0.4.7"

[dev-dependencies]
rstest = "0.18.1"
insta = { version = "1.31.0", features = ["yaml"] }
serde = "1.0.188"
itertools = "0.11.0"

[profile.dev.package.insta]
opt-level = 3
