[package]
name = "verver"
version = "0.1.0"
edition = "2021"

[dependencies]
winnow = "0.4.7"

[dev-dependencies]
rstest = "0.18.2"
insta = { version = "1.35.1", features = ["yaml"] }
serde = "1.0.197"
itertools = "0.12.1"

[profile.dev.package.insta]
opt-level = 3
