[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.lint]
install_crate = "clippy"
command = "cargo"
args = ["clippy", "--all-targets", "--all-features", "--", "-D", "warnings"]

[tasks.cov]
command = "cargo"
args = ["llvm-cov", "nextest", "--open", "--output-dir", ".coverage"]

[tasks.test]
command = "cargo"
args = ["nextest", "run"]

[tasks.test-watch]
command = "cargo"
args = ["watch", "-x", "nextest run"]