[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.cov]
command = "cargo"
args = ["llvm-cov", "nextest", "--open", "--output-dir", ".coverage"]

[tasks.test]
command = "cargo"
args = ["nextest", "run"]
