name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        toolchain:
          - stable
          - beta

    steps:
      - uses: actions/checkout@v3

      - name: Setup tooling
        run: |
          rustup update ${{ matrix.toolchain }} 
          rustup default ${{ matrix.toolchain }}
          rustup component add clippy
          rustup component add rustfmt

      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version

      - name: Using cache
        uses: Swatinem/rust-cache@v2.4.0
        with:
          cache-all-crates: "true"
          cache-on-failure: "true"

      - name: Install cargo-nextest
        uses: taiki-e/install-action@nextest

      - name: Check package
        run: cargo check

      - name: Check formatting
        run: cargo fmt -- --check

      - name: Lint
        run: cargo clippy -- -D warnings -A dead_code

      - name: Test
        run: cargo test

      - name: Build
        run: cargo build --release
