name: Test

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly

    steps:
      - uses: actions/checkout@v3

      - name: Setup tooling
        run: |
          rustup update ${{ matrix.toolchain }} 
          rustup default ${{ matrix.toolchain }}
          rustup component add clippy

      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version

      - name: Check package
        run: cargo check --verbose

      - name: Check formatting
        run: cargo fmt -- --check --verbose

      - name: Lint
        run: cargo clippy -- -F warnings

      - name: Test
        run: cargo test --verbose

      - name: Build
        run: cargo build --release --verbose
